files:
  - source: /src/main/resources/Server/Languages/en-US/*.lang
    translation: /src/main/resources/Server/Languages/%locale%/%original_file_name%
    update_option: update_as_unapproved
    type: properties
